package main;

import data.Progress;
import entity.NPC_Brock;
import entity.NPC_Door_Stopper;
import entity.NPC_Jonco;
import entity.NPC_Plimbo;
import entity.NPC_Ringold;
import entity.NPC_Rose;
import entity.NPC_Spaceship;
import entity.NPC_Spirit_Guy;
import entity.NPC_Trader;
import entity.NPC_Void_Brock;
import monster.MON_Batter;
import monster.MON_Cold_Mirror;
import monster.MON_Crow;
import monster.MON_ForgetMeNaut;
import monster.MON_MoonMonster;
import monster.MON_Poff;
import monster.MON_Undesired;
import monster.MON_Unwelcome;
import object.OBJ_Chest;
import object.OBJ_Chocolate;
import object.OBJ_Door;
import object.OBJ_Door_Dark;
import object.OBJ_Energy;
import object.OBJ_Green_Door;
import object.OBJ_Green_Key;
import object.OBJ_Heart;
import object.OBJ_Key;
import object.OBJ_Mini_Moon;
import object.OBJ_Moon_Coin;
import object.OBJ_Moon_Tree_Shield;
import object.OBJ_Ravaged_Shield;
import object.OBJ_Red_Door;
import object.OBJ_Red_Key;
import object.OBJ_Snowglobe;
import object.OBJ_Socks;
import object.OBJ_Tent;
import object.OBJ_Ash_Glove;
import object.OBJ_Blue_Door;
import object.OBJ_Boxing_Glove;
import tiles_interactive.IT_BurnedTree;
import tiles_interactive.IT_MetalPlate;
import tiles_interactive.IT_OldBrick;

public class AssetSetter {
	GamePanel gp; 
	
	public AssetSetter(GamePanel gp) {
		this.gp = gp; 
	}
	
	public void setObject() {
		// How to make OBJs:
		int mapNum = 0;
		int i = 0;
		gp.obj[mapNum][i] = new OBJ_Chocolate(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 35;
		gp.obj[mapNum][i].worldY = gp.tileSize * 27;
		i++;
		gp.obj[mapNum][i] = new OBJ_Moon_Coin(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 8;
		gp.obj[mapNum][i].worldY = gp.tileSize * 34;
		i++;
		gp.obj[mapNum][i] = new OBJ_Moon_Coin(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 23;
		gp.obj[mapNum][i].worldY = gp.tileSize * 24;
		i++;
		gp.obj[mapNum][i] = new OBJ_Moon_Coin(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 26;
		gp.obj[mapNum][i].worldY = gp.tileSize * 7;
		i++;
		gp.obj[mapNum][i] = new OBJ_Moon_Coin(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 14;
		gp.obj[mapNum][i].worldY = gp.tileSize * 25;
		i++;
		gp.obj[mapNum][i] = new OBJ_Chest(gp);
		gp.obj[mapNum][i].setLoot(new OBJ_Key(gp));
		gp.obj[mapNum][i].worldX = gp.tileSize * 38;
		gp.obj[mapNum][i].worldY = gp.tileSize * 9;
		i++;
		gp.obj[mapNum][i] = new OBJ_Ash_Glove(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 10;
		gp.obj[mapNum][i].worldY = gp.tileSize * 8;
		i++;
		gp.obj[mapNum][i] = new OBJ_Moon_Tree_Shield(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 38;
		gp.obj[mapNum][i].worldY = gp.tileSize * 42;
		i++;
		gp.obj[mapNum][i] = new OBJ_Heart(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 13;
		gp.obj[mapNum][i].worldY = gp.tileSize * 32;
		i++;
		gp.obj[mapNum][i] = new OBJ_Heart(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 33;
		gp.obj[mapNum][i].worldY = gp.tileSize * 7;
		i++;
		gp.obj[mapNum][i] = new OBJ_Energy(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 26;
		gp.obj[mapNum][i].worldY = gp.tileSize * 20;
		i++;
		gp.obj[mapNum][i] = new OBJ_Energy(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 18;
		gp.obj[mapNum][i].worldY = gp.tileSize * 39;
		i++;
		gp.obj[mapNum][i] = new OBJ_Door(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 14;
		gp.obj[mapNum][i].worldY = gp.tileSize * 28;
		i++;
		gp.obj[mapNum][i] = new OBJ_Door(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 10;
		gp.obj[mapNum][i].worldY = gp.tileSize * 11;
		i++;
		gp.obj[mapNum][i] = new OBJ_Mini_Moon(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 21;
		gp.obj[mapNum][i].worldY = gp.tileSize * 8;
		i++;
		gp.obj[mapNum][i] = new OBJ_Tent(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 31;
		gp.obj[mapNum][i].worldY = gp.tileSize * 42;
		i++;
		gp.obj[mapNum][i] = new OBJ_Red_Door(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 14;
		gp.obj[mapNum][i].worldY = gp.tileSize * 42;
		i++;
		gp.obj[mapNum][i] = new OBJ_Blue_Door(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 16;
		gp.obj[mapNum][i].worldY = gp.tileSize * 42;
		i++;
		gp.obj[mapNum][i] = new OBJ_Green_Door(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 18;
		gp.obj[mapNum][i].worldY = gp.tileSize * 42;
		i++;
		
		mapNum = 3;
		i = 0;
		gp.obj[mapNum][i] = new OBJ_Chest(gp);
		gp.obj[mapNum][i].setLoot(new OBJ_Boxing_Glove(gp));
		gp.obj[mapNum][i].worldX = gp.tileSize * 18;
		gp.obj[mapNum][i].worldY = gp.tileSize * 42;
		i++;
		gp.obj[mapNum][i] = new OBJ_Chest(gp);
		gp.obj[mapNum][i].setLoot(new OBJ_Ravaged_Shield(gp));
		gp.obj[mapNum][i].worldX = gp.tileSize * 14;
		gp.obj[mapNum][i].worldY = gp.tileSize * 42;
		i++;
		gp.obj[mapNum][i] = new OBJ_Chest(gp);
		gp.obj[mapNum][i].setLoot(new OBJ_Chocolate(gp));
		gp.obj[mapNum][i].worldX = gp.tileSize * 19;
		gp.obj[mapNum][i].worldY = gp.tileSize * 36;
		i++;
		gp.obj[mapNum][i] = new OBJ_Door_Dark(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 14;
		gp.obj[mapNum][i].worldY = gp.tileSize * 33;
		i++;
		
		mapNum = 4;
		i = 0;
		gp.obj[mapNum][i] = new OBJ_Door_Dark(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 20;
		gp.obj[mapNum][i].worldY = gp.tileSize * 7;
		i++;
		gp.obj[mapNum][i] = new OBJ_Snowglobe(gp);
		gp.obj[mapNum][i].worldX = gp.tileSize * 20;
		gp.obj[mapNum][i].worldY = gp.tileSize * 1;
		i++;
		
		mapNum = 6; 
		i = 0;
		gp.obj[mapNum][i] = new OBJ_Chest(gp);
		gp.obj[mapNum][i].setLoot(new OBJ_Green_Key(gp));
		gp.obj[mapNum][i].worldX = gp.tileSize * 22;
		gp.obj[mapNum][i].worldY = gp.tileSize * 26;
		i++;
		
		mapNum = 7; 
		i = 0;
		gp.obj[mapNum][i] = new OBJ_Chest(gp);
		gp.obj[mapNum][i].setLoot(new OBJ_Red_Key(gp));
		gp.obj[mapNum][i].worldX = gp.tileSize * 20;
		gp.obj[mapNum][i].worldY = gp.tileSize * 33;
		i++;
	}
	
	public void setNPC(){	
		int mapNum = 0;
		int i = 0;
		gp.npc[mapNum][i] = new NPC_Brock(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 21;
		gp.npc[mapNum][i].worldY = gp.tileSize * 21;
		i++;
		gp.npc[mapNum][i] = new NPC_Spirit_Guy(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 38;
		gp.npc[mapNum][i].worldY = gp.tileSize * 10;
		i++;
		gp.npc[mapNum][i] = new NPC_Plimbo(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 25;
		gp.npc[mapNum][i].worldY = gp.tileSize * 8;
		i++;
		gp.npc[mapNum][i] = new NPC_Spaceship(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 25;
		gp.npc[mapNum][i].worldY = gp.tileSize * 19;
		i++;
		gp.npc[mapNum][i] = new NPC_Ringold(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 38;
		gp.npc[mapNum][i].worldY = gp.tileSize * 36;
		i++;
		gp.npc[mapNum][i] = new NPC_Jonco(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 25;
		gp.npc[mapNum][i].worldY = gp.tileSize * 22;
		i++;
		mapNum = 1;
		i = 0;
		gp.npc[mapNum][i] = new NPC_Trader(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 11;
		gp.npc[mapNum][i].worldY = gp.tileSize * 7;
		mapNum = 2;
		i = 0;
		gp.npc[mapNum][i] = new NPC_Void_Brock(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 12;
		gp.npc[mapNum][i].worldY = gp.tileSize * 12;
		
		mapNum = 3;
		i = 0;
		gp.npc[mapNum][i] = new NPC_Door_Stopper(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 11;
		gp.npc[mapNum][i].worldY = gp.tileSize * 46;
		i++;
		gp.npc[mapNum][i] = new NPC_Door_Stopper(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 22;
		gp.npc[mapNum][i].worldY = gp.tileSize * 43;
		i++;
		gp.npc[mapNum][i] = new NPC_Door_Stopper(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 6;
		gp.npc[mapNum][i].worldY = gp.tileSize * 35;
		i++;
		
		mapNum = 7; 
		i = 0;
		gp.npc[mapNum][i] = new NPC_Rose(gp);
		gp.npc[mapNum][i].worldX = gp.tileSize * 20;
		gp.npc[mapNum][i].worldY = gp.tileSize * 34;
		i++;
	}
	
	public void setMonster() {
		int mapNum = 0;
		int i = 0;
		gp.monster[mapNum][i] = new MON_MoonMonster(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*21;
		gp.monster[mapNum][i].worldY = gp.tileSize*37;
		i++;
		gp.monster[mapNum][i] = new MON_MoonMonster(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*21;
		gp.monster[mapNum][i].worldY = gp.tileSize*38;
		i++; 
		gp.monster[mapNum][i] = new MON_MoonMonster(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*22;
		gp.monster[mapNum][i].worldY = gp.tileSize*38;
		i++;  
		gp.monster[mapNum][i] = new MON_Batter(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*11;
		gp.monster[mapNum][i].worldY = gp.tileSize*32;
		i++; 
		
		mapNum = 2;
		i = 0;
		gp.monster[mapNum][i] = new MON_Unwelcome(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*4;
		gp.monster[mapNum][i].worldY = gp.tileSize*10;
		i++;
		gp.monster[mapNum][i] = new MON_Unwelcome(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*10;
		gp.monster[mapNum][i].worldY = gp.tileSize*10;
		i++;
		gp.monster[mapNum][i] = new MON_Unwelcome(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*20;
		gp.monster[mapNum][i].worldY = gp.tileSize*20;
		i++;
		gp.monster[mapNum][i] = new MON_Unwelcome(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*32;
		gp.monster[mapNum][i].worldY = gp.tileSize*13;
		i++;
		gp.monster[mapNum][i] = new MON_Unwelcome(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*20;
		gp.monster[mapNum][i].worldY = gp.tileSize*10;
		i++;
		
		mapNum = 3;
		i = 0;
		gp.monster[mapNum][i] = new MON_Undesired(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*22;
		gp.monster[mapNum][i].worldY = gp.tileSize*44;
		i++;
		gp.monster[mapNum][i] = new MON_Undesired(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*8;
		gp.monster[mapNum][i].worldY = gp.tileSize*35;
		i++;
		gp.monster[mapNum][i] = new MON_Undesired(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*4;
		gp.monster[mapNum][i].worldY = gp.tileSize*10;
		i++;
		
		mapNum = 4;
		i = 0;
		if (!Progress.forgetMeNautDefeated) {
			gp.monster[mapNum][i] = new MON_ForgetMeNaut(gp);
			gp.monster[mapNum][i].worldX = gp.tileSize*19;
			gp.monster[mapNum][i].worldY = gp.tileSize*19;
			i++;	
		}
		
		mapNum = 5;
		i = 0;
		gp.monster[mapNum][i] = new MON_Poff(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*33;
		gp.monster[mapNum][i].worldY = gp.tileSize*15;
		i++;
		gp.monster[mapNum][i] = new MON_Poff(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*20;
		gp.monster[mapNum][i].worldY = gp.tileSize*10;
		i++;
		gp.monster[mapNum][i] = new MON_Poff(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*40;
		gp.monster[mapNum][i].worldY = gp.tileSize*15;
		i++;
		gp.monster[mapNum][i] = new MON_Poff(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*33;
		gp.monster[mapNum][i].worldY = gp.tileSize*25;
		i++;
		gp.monster[mapNum][i] = new MON_Poff(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*15;
		gp.monster[mapNum][i].worldY = gp.tileSize*15;
		i++;
		gp.monster[mapNum][i] = new MON_Cold_Mirror(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*34;
		gp.monster[mapNum][i].worldY = gp.tileSize*15;
		i++;
		
		mapNum = 6;
		i = 0;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*33;
		gp.monster[mapNum][i].worldY = gp.tileSize*15;
		i++;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*16;
		gp.monster[mapNum][i].worldY = gp.tileSize*12;
		i++;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*33;
		gp.monster[mapNum][i].worldY = gp.tileSize*36;
		i++;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*12;
		gp.monster[mapNum][i].worldY = gp.tileSize*29;
		i++;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*26;
		gp.monster[mapNum][i].worldY = gp.tileSize*14;
		i++;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*27;
		gp.monster[mapNum][i].worldY = gp.tileSize*34;
		i++;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*14;
		gp.monster[mapNum][i].worldY = gp.tileSize*23;
		i++;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*21;
		gp.monster[mapNum][i].worldY = gp.tileSize*32;
		i++;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*21;
		gp.monster[mapNum][i].worldY = gp.tileSize*18;
		i++;
		gp.monster[mapNum][i] = new MON_Crow(gp);
		gp.monster[mapNum][i].worldX = gp.tileSize*18;
		gp.monster[mapNum][i].worldY = gp.tileSize*26;
		i++;
	}	
	
	public void setInteractiveTile() {
		int mapNum = 0;
		int i = 0;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 40, 11); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 35, 10); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 37, 8); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 38, 41); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 37, 42); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 23, 25); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 23, 26); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 23, 27); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 23, 35); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 23, 34); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 23, 33); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 17, 40); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 16, 40); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 15, 40); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 14, 40); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 13, 40); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 39, 42); i++;
		gp.iTile[mapNum][i] = new IT_BurnedTree(gp, 40, 42); i++;
		
		mapNum = 3; 
		i = 0;
		gp.iTile[mapNum][i] = new IT_OldBrick(gp, 14, 44); i++;
		gp.iTile[mapNum][i] = new IT_OldBrick(gp, 10, 33); i++;
		gp.iTile[mapNum][i] = new IT_OldBrick(gp, 10, 32); i++;
		gp.iTile[mapNum][i] = new IT_OldBrick(gp, 17, 36); i++;
		gp.iTile[mapNum][i] = new IT_OldBrick(gp, 9, 27); i++;
		gp.iTile[mapNum][i] = new IT_OldBrick(gp, 8, 26); i++;
		gp.iTile[mapNum][i] = new IT_OldBrick(gp, 6, 23); i++;
		
		gp.iTile[mapNum][i] = new IT_MetalPlate(gp, 12, 46); i++;
		gp.iTile[mapNum][i] = new IT_MetalPlate(gp, 23, 41); i++;
		gp.iTile[mapNum][i] = new IT_MetalPlate(gp, 12, 35); i++;
		
		
	}
}
